schema_version: 1

context:
  name: blessings
  version: 1.7

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 98e5854d805f50a5b58ac2333411b0482516a8210f23f43308baeb58d77c157d

build:
  number: 1010
  skip: win
  script: python -m pip install . -vv --no-build-isolation --no-deps

requirements:
  build:
    - if: build_platform != target_platform
      then:
      - python
      - cross-python_${{ target_platform }}
  host:
    - python
    - setuptools
    - pip
  run:
    - python
    - six

tests:
  - python:
      imports:
        - blessings
      pip_check: true

about:
  license: MIT
  license_file: LICENSE
  summary: A thin, practical wrapper around terminal capabilities in Python
  homepage: https://github.com/erikrose/blessings
  repository: https://github.com/erikrose/blessings

extra:
  recipe-maintainers:
    - synapticarbors
